Adding example functions for more DB operations
cloudspannerecosystem/dynamodb-adapter pull request #48
Opened 2021-10-25 16:15 UTC by gushob21

Fixes #37 

> It's a good idea to open an issue first for discussion.

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

2021-11-02 21:36 UTC, bgood requested changes
Couple comments on reusing types, but also a nit on indentation and stray white space.

2021-11-02 21:36 UTC, bgood commented on examples/golang/main.go
> +  type Manufacturers struct {
Let's move these to types.go

2021-11-02 21:36 UTC, bgood commented on examples/golang/main.go
> +  type Item struct {
Why not use the existing types or make a new `CustomerSummary` type or something like that.

2021-11-05 15:54 UTC, gushob21 reviewed
@bgood made changes as suggested. Please review them.

2021-11-05 15:56 UTC, bgood approved these changes

2021-11-05 15:57 UTC, bgood commented
LGTM

Thank you!

2021-11-05 15:57 UTC, merged